#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright 2009 Keith Stribley http://www.thanlwinsoft.org/ 
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <http://www.gnu.org/licenses/>.

import sys
from thanlwinsoft.translate.podiffgtk import PoDiffGtk

# main method
if __name__ == "__main__":
    base = PoDiffGtk()
    if (len(sys.argv) == 3) :
        base.diff(sys.argv[1], sys.argv[2])
    else :
        if  len(sys.argv) == 5 :
            base.merge(sys.argv[1], sys.argv[2],sys.argv[3], sys.argv[4])
        else :
            if (len(sys.argv) != 1):
                print _("Usage: {0} fileA fileB").format(sys.argv[0])
                print _("or     {0} base fileA fileB merge-output").format(sys.argv[0])
                print _("or     {0}").format(sys.argv[0])
                sys.exit(1)
    base.main()

